runtime: nodejs
env: flex
automatic_scaling:
  max_num_instances: 1
# Use only a single instance, so that this local-memory-only chat app will work
# consistently with multiple users. To work across multiple instances, an
# extra-instance messaging system or data store would be needed.

network:
  session_affinity: true
# [END appengine_websockets_yaml]
