version: "3"
services: 
    client:
        stdin_open: true
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "3003:3003"
        volumes: 
            - ".:/app"